// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package db

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CountBooks provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CountBooks(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountBooks")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CountBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBooks'
type MockQuerier_CountBooks_Call struct {
	*mock.Call
}

// CountBooks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) CountBooks(ctx interface{}) *MockQuerier_CountBooks_Call {
	return &MockQuerier_CountBooks_Call{Call: _e.mock.On("CountBooks", ctx)}
}

func (_c *MockQuerier_CountBooks_Call) Run(run func(ctx context.Context)) *MockQuerier_CountBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuerier_CountBooks_Call) Return(n int64, err error) *MockQuerier_CountBooks_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuerier_CountBooks_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockQuerier_CountBooks_Call {
	_c.Call.Return(run)
	return _c
}

// CountSeries provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CountSeries(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountSeries")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CountSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSeries'
type MockQuerier_CountSeries_Call struct {
	*mock.Call
}

// CountSeries is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) CountSeries(ctx interface{}) *MockQuerier_CountSeries_Call {
	return &MockQuerier_CountSeries_Call{Call: _e.mock.On("CountSeries", ctx)}
}

func (_c *MockQuerier_CountSeries_Call) Run(run func(ctx context.Context)) *MockQuerier_CountSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQuerier_CountSeries_Call) Return(n int64, err error) *MockQuerier_CountSeries_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuerier_CountSeries_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockQuerier_CountSeries_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBook provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateBook")
	}

	var r0 Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateBookParams) (Book, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateBookParams) Book); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateBookParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBook'
type MockQuerier_CreateBook_Call struct {
	*mock.Call
}

// CreateBook is a helper method to define mock.On call
//   - ctx context.Context
//   - arg CreateBookParams
func (_e *MockQuerier_Expecter) CreateBook(ctx interface{}, arg interface{}) *MockQuerier_CreateBook_Call {
	return &MockQuerier_CreateBook_Call{Call: _e.mock.On("CreateBook", ctx, arg)}
}

func (_c *MockQuerier_CreateBook_Call) Run(run func(ctx context.Context, arg CreateBookParams)) *MockQuerier_CreateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateBookParams
		if args[1] != nil {
			arg1 = args[1].(CreateBookParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateBook_Call) Return(book Book, err error) *MockQuerier_CreateBook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockQuerier_CreateBook_Call) RunAndReturn(run func(ctx context.Context, arg CreateBookParams) (Book, error)) *MockQuerier_CreateBook_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMissingBook provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateMissingBook(ctx context.Context, arg CreateMissingBookParams) (Book, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateMissingBook")
	}

	var r0 Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateMissingBookParams) (Book, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateMissingBookParams) Book); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateMissingBookParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateMissingBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMissingBook'
type MockQuerier_CreateMissingBook_Call struct {
	*mock.Call
}

// CreateMissingBook is a helper method to define mock.On call
//   - ctx context.Context
//   - arg CreateMissingBookParams
func (_e *MockQuerier_Expecter) CreateMissingBook(ctx interface{}, arg interface{}) *MockQuerier_CreateMissingBook_Call {
	return &MockQuerier_CreateMissingBook_Call{Call: _e.mock.On("CreateMissingBook", ctx, arg)}
}

func (_c *MockQuerier_CreateMissingBook_Call) Run(run func(ctx context.Context, arg CreateMissingBookParams)) *MockQuerier_CreateMissingBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateMissingBookParams
		if args[1] != nil {
			arg1 = args[1].(CreateMissingBookParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateMissingBook_Call) Return(book Book, err error) *MockQuerier_CreateMissingBook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockQuerier_CreateMissingBook_Call) RunAndReturn(run func(ctx context.Context, arg CreateMissingBookParams) (Book, error)) *MockQuerier_CreateMissingBook_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSeries provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateSeries(ctx context.Context, arg CreateSeriesParams) (Series, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateSeries")
	}

	var r0 Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateSeriesParams) (Series, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateSeriesParams) Series); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(Series)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateSeriesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSeries'
type MockQuerier_CreateSeries_Call struct {
	*mock.Call
}

// CreateSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - arg CreateSeriesParams
func (_e *MockQuerier_Expecter) CreateSeries(ctx interface{}, arg interface{}) *MockQuerier_CreateSeries_Call {
	return &MockQuerier_CreateSeries_Call{Call: _e.mock.On("CreateSeries", ctx, arg)}
}

func (_c *MockQuerier_CreateSeries_Call) Run(run func(ctx context.Context, arg CreateSeriesParams)) *MockQuerier_CreateSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateSeriesParams
		if args[1] != nil {
			arg1 = args[1].(CreateSeriesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateSeries_Call) Return(series Series, err error) *MockQuerier_CreateSeries_Call {
	_c.Call.Return(series, err)
	return _c
}

func (_c *MockQuerier_CreateSeries_Call) RunAndReturn(run func(ctx context.Context, arg CreateSeriesParams) (Series, error)) *MockQuerier_CreateSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorByName provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetAuthorByName(ctx context.Context, name string) (Author, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorByName")
	}

	var r0 Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Author, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Author); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(Author)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetAuthorByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorByName'
type MockQuerier_GetAuthorByName_Call struct {
	*mock.Call
}

// GetAuthorByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQuerier_Expecter) GetAuthorByName(ctx interface{}, name interface{}) *MockQuerier_GetAuthorByName_Call {
	return &MockQuerier_GetAuthorByName_Call{Call: _e.mock.On("GetAuthorByName", ctx, name)}
}

func (_c *MockQuerier_GetAuthorByName_Call) Run(run func(ctx context.Context, name string)) *MockQuerier_GetAuthorByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetAuthorByName_Call) Return(author Author, err error) *MockQuerier_GetAuthorByName_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockQuerier_GetAuthorByName_Call) RunAndReturn(run func(ctx context.Context, name string) (Author, error)) *MockQuerier_GetAuthorByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorsForBook provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetAuthorsForBook(ctx context.Context, bookID int64) ([]Author, error) {
	ret := _mock.Called(ctx, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorsForBook")
	}

	var r0 []Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]Author, error)); ok {
		return returnFunc(ctx, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []Author); ok {
		r0 = returnFunc(ctx, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetAuthorsForBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorsForBook'
type MockQuerier_GetAuthorsForBook_Call struct {
	*mock.Call
}

// GetAuthorsForBook is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID int64
func (_e *MockQuerier_Expecter) GetAuthorsForBook(ctx interface{}, bookID interface{}) *MockQuerier_GetAuthorsForBook_Call {
	return &MockQuerier_GetAuthorsForBook_Call{Call: _e.mock.On("GetAuthorsForBook", ctx, bookID)}
}

func (_c *MockQuerier_GetAuthorsForBook_Call) Run(run func(ctx context.Context, bookID int64)) *MockQuerier_GetAuthorsForBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetAuthorsForBook_Call) Return(authors []Author, err error) *MockQuerier_GetAuthorsForBook_Call {
	_c.Call.Return(authors, err)
	return _c
}

func (_c *MockQuerier_GetAuthorsForBook_Call) RunAndReturn(run func(ctx context.Context, bookID int64) ([]Author, error)) *MockQuerier_GetAuthorsForBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetBook provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetBook(ctx context.Context, id int64) (Book, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetBook")
	}

	var r0 Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (Book, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) Book); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBook'
type MockQuerier_GetBook_Call struct {
	*mock.Call
}

// GetBook is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQuerier_Expecter) GetBook(ctx interface{}, id interface{}) *MockQuerier_GetBook_Call {
	return &MockQuerier_GetBook_Call{Call: _e.mock.On("GetBook", ctx, id)}
}

func (_c *MockQuerier_GetBook_Call) Run(run func(ctx context.Context, id int64)) *MockQuerier_GetBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetBook_Call) Return(book Book, err error) *MockQuerier_GetBook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockQuerier_GetBook_Call) RunAndReturn(run func(ctx context.Context, id int64) (Book, error)) *MockQuerier_GetBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByBookID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetBookByBookID(ctx context.Context, bookID int64) (Book, error) {
	ret := _mock.Called(ctx, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByBookID")
	}

	var r0 Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (Book, error)); ok {
		return returnFunc(ctx, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) Book); ok {
		r0 = returnFunc(ctx, bookID)
	} else {
		r0 = ret.Get(0).(Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetBookByBookID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByBookID'
type MockQuerier_GetBookByBookID_Call struct {
	*mock.Call
}

// GetBookByBookID is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID int64
func (_e *MockQuerier_Expecter) GetBookByBookID(ctx interface{}, bookID interface{}) *MockQuerier_GetBookByBookID_Call {
	return &MockQuerier_GetBookByBookID_Call{Call: _e.mock.On("GetBookByBookID", ctx, bookID)}
}

func (_c *MockQuerier_GetBookByBookID_Call) Run(run func(ctx context.Context, bookID int64)) *MockQuerier_GetBookByBookID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetBookByBookID_Call) Return(book Book, err error) *MockQuerier_GetBookByBookID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockQuerier_GetBookByBookID_Call) RunAndReturn(run func(ctx context.Context, bookID int64) (Book, error)) *MockQuerier_GetBookByBookID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksBySeries provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetBooksBySeries(ctx context.Context, seriesID *int64) ([]Book, error) {
	ret := _mock.Called(ctx, seriesID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksBySeries")
	}

	var r0 []Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64) ([]Book, error)); ok {
		return returnFunc(ctx, seriesID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *int64) []Book); ok {
		r0 = returnFunc(ctx, seriesID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *int64) error); ok {
		r1 = returnFunc(ctx, seriesID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetBooksBySeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksBySeries'
type MockQuerier_GetBooksBySeries_Call struct {
	*mock.Call
}

// GetBooksBySeries is a helper method to define mock.On call
//   - ctx context.Context
//   - seriesID *int64
func (_e *MockQuerier_Expecter) GetBooksBySeries(ctx interface{}, seriesID interface{}) *MockQuerier_GetBooksBySeries_Call {
	return &MockQuerier_GetBooksBySeries_Call{Call: _e.mock.On("GetBooksBySeries", ctx, seriesID)}
}

func (_c *MockQuerier_GetBooksBySeries_Call) Run(run func(ctx context.Context, seriesID *int64)) *MockQuerier_GetBooksBySeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetBooksBySeries_Call) Return(books []Book, err error) *MockQuerier_GetBooksBySeries_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockQuerier_GetBooksBySeries_Call) RunAndReturn(run func(ctx context.Context, seriesID *int64) ([]Book, error)) *MockQuerier_GetBooksBySeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetConfig(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockQuerier_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockQuerier_Expecter) GetConfig(ctx interface{}, key interface{}) *MockQuerier_GetConfig_Call {
	return &MockQuerier_GetConfig_Call{Call: _e.mock.On("GetConfig", ctx, key)}
}

func (_c *MockQuerier_GetConfig_Call) Run(run func(ctx context.Context, key string)) *MockQuerier_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetConfig_Call) Return(s string, err error) *MockQuerier_GetConfig_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockQuerier_GetConfig_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockQuerier_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetMultipleConfig provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetMultipleConfig(ctx context.Context, key string) ([]Configuration, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetMultipleConfig")
	}

	var r0 []Configuration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]Configuration, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []Configuration); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Configuration)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetMultipleConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMultipleConfig'
type MockQuerier_GetMultipleConfig_Call struct {
	*mock.Call
}

// GetMultipleConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockQuerier_Expecter) GetMultipleConfig(ctx interface{}, key interface{}) *MockQuerier_GetMultipleConfig_Call {
	return &MockQuerier_GetMultipleConfig_Call{Call: _e.mock.On("GetMultipleConfig", ctx, key)}
}

func (_c *MockQuerier_GetMultipleConfig_Call) Run(run func(ctx context.Context, key string)) *MockQuerier_GetMultipleConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetMultipleConfig_Call) Return(configurations []Configuration, err error) *MockQuerier_GetMultipleConfig_Call {
	_c.Call.Return(configurations, err)
	return _c
}

func (_c *MockQuerier_GetMultipleConfig_Call) RunAndReturn(run func(ctx context.Context, key string) ([]Configuration, error)) *MockQuerier_GetMultipleConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeries provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetSeries(ctx context.Context, id int64) (Series, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetSeries")
	}

	var r0 Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (Series, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) Series); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(Series)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeries'
type MockQuerier_GetSeries_Call struct {
	*mock.Call
}

// GetSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQuerier_Expecter) GetSeries(ctx interface{}, id interface{}) *MockQuerier_GetSeries_Call {
	return &MockQuerier_GetSeries_Call{Call: _e.mock.On("GetSeries", ctx, id)}
}

func (_c *MockQuerier_GetSeries_Call) Run(run func(ctx context.Context, id int64)) *MockQuerier_GetSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetSeries_Call) Return(series Series, err error) *MockQuerier_GetSeries_Call {
	_c.Call.Return(series, err)
	return _c
}

func (_c *MockQuerier_GetSeries_Call) RunAndReturn(run func(ctx context.Context, id int64) (Series, error)) *MockQuerier_GetSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeriesAuthors provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetSeriesAuthors(ctx context.Context, seriesID int64) ([]Author, error) {
	ret := _mock.Called(ctx, seriesID)

	if len(ret) == 0 {
		panic("no return value specified for GetSeriesAuthors")
	}

	var r0 []Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]Author, error)); ok {
		return returnFunc(ctx, seriesID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []Author); ok {
		r0 = returnFunc(ctx, seriesID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, seriesID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetSeriesAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeriesAuthors'
type MockQuerier_GetSeriesAuthors_Call struct {
	*mock.Call
}

// GetSeriesAuthors is a helper method to define mock.On call
//   - ctx context.Context
//   - seriesID int64
func (_e *MockQuerier_Expecter) GetSeriesAuthors(ctx interface{}, seriesID interface{}) *MockQuerier_GetSeriesAuthors_Call {
	return &MockQuerier_GetSeriesAuthors_Call{Call: _e.mock.On("GetSeriesAuthors", ctx, seriesID)}
}

func (_c *MockQuerier_GetSeriesAuthors_Call) Run(run func(ctx context.Context, seriesID int64)) *MockQuerier_GetSeriesAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetSeriesAuthors_Call) Return(authors []Author, err error) *MockQuerier_GetSeriesAuthors_Call {
	_c.Call.Return(authors, err)
	return _c
}

func (_c *MockQuerier_GetSeriesAuthors_Call) RunAndReturn(run func(ctx context.Context, seriesID int64) ([]Author, error)) *MockQuerier_GetSeriesAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeriesByGoodreadsID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetSeriesByGoodreadsID(ctx context.Context, seriesID int64) (Series, error) {
	ret := _mock.Called(ctx, seriesID)

	if len(ret) == 0 {
		panic("no return value specified for GetSeriesByGoodreadsID")
	}

	var r0 Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (Series, error)); ok {
		return returnFunc(ctx, seriesID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) Series); ok {
		r0 = returnFunc(ctx, seriesID)
	} else {
		r0 = ret.Get(0).(Series)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, seriesID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetSeriesByGoodreadsID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeriesByGoodreadsID'
type MockQuerier_GetSeriesByGoodreadsID_Call struct {
	*mock.Call
}

// GetSeriesByGoodreadsID is a helper method to define mock.On call
//   - ctx context.Context
//   - seriesID int64
func (_e *MockQuerier_Expecter) GetSeriesByGoodreadsID(ctx interface{}, seriesID interface{}) *MockQuerier_GetSeriesByGoodreadsID_Call {
	return &MockQuerier_GetSeriesByGoodreadsID_Call{Call: _e.mock.On("GetSeriesByGoodreadsID", ctx, seriesID)}
}

func (_c *MockQuerier_GetSeriesByGoodreadsID_Call) Run(run func(ctx context.Context, seriesID int64)) *MockQuerier_GetSeriesByGoodreadsID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetSeriesByGoodreadsID_Call) Return(series Series, err error) *MockQuerier_GetSeriesByGoodreadsID_Call {
	_c.Call.Return(series, err)
	return _c
}

func (_c *MockQuerier_GetSeriesByGoodreadsID_Call) RunAndReturn(run func(ctx context.Context, seriesID int64) (Series, error)) *MockQuerier_GetSeriesByGoodreadsID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeriesBySeriesID provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetSeriesBySeriesID(ctx context.Context, seriesID int64) (Series, error) {
	ret := _mock.Called(ctx, seriesID)

	if len(ret) == 0 {
		panic("no return value specified for GetSeriesBySeriesID")
	}

	var r0 Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (Series, error)); ok {
		return returnFunc(ctx, seriesID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) Series); ok {
		r0 = returnFunc(ctx, seriesID)
	} else {
		r0 = ret.Get(0).(Series)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, seriesID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetSeriesBySeriesID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeriesBySeriesID'
type MockQuerier_GetSeriesBySeriesID_Call struct {
	*mock.Call
}

// GetSeriesBySeriesID is a helper method to define mock.On call
//   - ctx context.Context
//   - seriesID int64
func (_e *MockQuerier_Expecter) GetSeriesBySeriesID(ctx interface{}, seriesID interface{}) *MockQuerier_GetSeriesBySeriesID_Call {
	return &MockQuerier_GetSeriesBySeriesID_Call{Call: _e.mock.On("GetSeriesBySeriesID", ctx, seriesID)}
}

func (_c *MockQuerier_GetSeriesBySeriesID_Call) Run(run func(ctx context.Context, seriesID int64)) *MockQuerier_GetSeriesBySeriesID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetSeriesBySeriesID_Call) Return(series Series, err error) *MockQuerier_GetSeriesBySeriesID_Call {
	_c.Call.Return(series, err)
	return _c
}

func (_c *MockQuerier_GetSeriesBySeriesID_Call) RunAndReturn(run func(ctx context.Context, seriesID int64) (Series, error)) *MockQuerier_GetSeriesBySeriesID_Call {
	_c.Call.Return(run)
	return _c
}

// LinkBookAuthor provides a mock function for the type MockQuerier
func (_mock *MockQuerier) LinkBookAuthor(ctx context.Context, arg LinkBookAuthorParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for LinkBookAuthor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, LinkBookAuthorParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_LinkBookAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkBookAuthor'
type MockQuerier_LinkBookAuthor_Call struct {
	*mock.Call
}

// LinkBookAuthor is a helper method to define mock.On call
//   - ctx context.Context
//   - arg LinkBookAuthorParams
func (_e *MockQuerier_Expecter) LinkBookAuthor(ctx interface{}, arg interface{}) *MockQuerier_LinkBookAuthor_Call {
	return &MockQuerier_LinkBookAuthor_Call{Call: _e.mock.On("LinkBookAuthor", ctx, arg)}
}

func (_c *MockQuerier_LinkBookAuthor_Call) Run(run func(ctx context.Context, arg LinkBookAuthorParams)) *MockQuerier_LinkBookAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 LinkBookAuthorParams
		if args[1] != nil {
			arg1 = args[1].(LinkBookAuthorParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_LinkBookAuthor_Call) Return(err error) *MockQuerier_LinkBookAuthor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_LinkBookAuthor_Call) RunAndReturn(run func(ctx context.Context, arg LinkBookAuthorParams) error) *MockQuerier_LinkBookAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// LinkSeriesAuthor provides a mock function for the type MockQuerier
func (_mock *MockQuerier) LinkSeriesAuthor(ctx context.Context, arg LinkSeriesAuthorParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for LinkSeriesAuthor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, LinkSeriesAuthorParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_LinkSeriesAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LinkSeriesAuthor'
type MockQuerier_LinkSeriesAuthor_Call struct {
	*mock.Call
}

// LinkSeriesAuthor is a helper method to define mock.On call
//   - ctx context.Context
//   - arg LinkSeriesAuthorParams
func (_e *MockQuerier_Expecter) LinkSeriesAuthor(ctx interface{}, arg interface{}) *MockQuerier_LinkSeriesAuthor_Call {
	return &MockQuerier_LinkSeriesAuthor_Call{Call: _e.mock.On("LinkSeriesAuthor", ctx, arg)}
}

func (_c *MockQuerier_LinkSeriesAuthor_Call) Run(run func(ctx context.Context, arg LinkSeriesAuthorParams)) *MockQuerier_LinkSeriesAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 LinkSeriesAuthorParams
		if args[1] != nil {
			arg1 = args[1].(LinkSeriesAuthorParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_LinkSeriesAuthor_Call) Return(err error) *MockQuerier_LinkSeriesAuthor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_LinkSeriesAuthor_Call) RunAndReturn(run func(ctx context.Context, arg LinkSeriesAuthorParams) error) *MockQuerier_LinkSeriesAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// ListBooks provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListBooks")
	}

	var r0 []Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListBooksParams) ([]Book, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListBooksParams) []Book); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ListBooksParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBooks'
type MockQuerier_ListBooks_Call struct {
	*mock.Call
}

// ListBooks is a helper method to define mock.On call
//   - ctx context.Context
//   - arg ListBooksParams
func (_e *MockQuerier_Expecter) ListBooks(ctx interface{}, arg interface{}) *MockQuerier_ListBooks_Call {
	return &MockQuerier_ListBooks_Call{Call: _e.mock.On("ListBooks", ctx, arg)}
}

func (_c *MockQuerier_ListBooks_Call) Run(run func(ctx context.Context, arg ListBooksParams)) *MockQuerier_ListBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ListBooksParams
		if args[1] != nil {
			arg1 = args[1].(ListBooksParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListBooks_Call) Return(books []Book, err error) *MockQuerier_ListBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockQuerier_ListBooks_Call) RunAndReturn(run func(ctx context.Context, arg ListBooksParams) ([]Book, error)) *MockQuerier_ListBooks_Call {
	_c.Call.Return(run)
	return _c
}

// ListSeries provides a mock function for the type MockQuerier
func (_mock *MockQuerier) ListSeries(ctx context.Context, arg ListSeriesParams) ([]Series, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListSeries")
	}

	var r0 []Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListSeriesParams) ([]Series, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ListSeriesParams) []Series); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Series)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ListSeriesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_ListSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSeries'
type MockQuerier_ListSeries_Call struct {
	*mock.Call
}

// ListSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - arg ListSeriesParams
func (_e *MockQuerier_Expecter) ListSeries(ctx interface{}, arg interface{}) *MockQuerier_ListSeries_Call {
	return &MockQuerier_ListSeries_Call{Call: _e.mock.On("ListSeries", ctx, arg)}
}

func (_c *MockQuerier_ListSeries_Call) Run(run func(ctx context.Context, arg ListSeriesParams)) *MockQuerier_ListSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ListSeriesParams
		if args[1] != nil {
			arg1 = args[1].(ListSeriesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_ListSeries_Call) Return(seriess []Series, err error) *MockQuerier_ListSeries_Call {
	_c.Call.Return(seriess, err)
	return _c
}

func (_c *MockQuerier_ListSeries_Call) RunAndReturn(run func(ctx context.Context, arg ListSeriesParams) ([]Series, error)) *MockQuerier_ListSeries_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockQuerier
func (_mock *MockQuerier) SetConfig(ctx context.Context, arg SetConfigParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SetConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, SetConfigParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockQuerier_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - arg SetConfigParams
func (_e *MockQuerier_Expecter) SetConfig(ctx interface{}, arg interface{}) *MockQuerier_SetConfig_Call {
	return &MockQuerier_SetConfig_Call{Call: _e.mock.On("SetConfig", ctx, arg)}
}

func (_c *MockQuerier_SetConfig_Call) Run(run func(ctx context.Context, arg SetConfigParams)) *MockQuerier_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 SetConfigParams
		if args[1] != nil {
			arg1 = args[1].(SetConfigParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_SetConfig_Call) Return(err error) *MockQuerier_SetConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_SetConfig_Call) RunAndReturn(run func(ctx context.Context, arg SetConfigParams) error) *MockQuerier_SetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBookSeries provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateBookSeries(ctx context.Context, arg UpdateBookSeriesParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBookSeries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpdateBookSeriesParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_UpdateBookSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBookSeries'
type MockQuerier_UpdateBookSeries_Call struct {
	*mock.Call
}

// UpdateBookSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - arg UpdateBookSeriesParams
func (_e *MockQuerier_Expecter) UpdateBookSeries(ctx interface{}, arg interface{}) *MockQuerier_UpdateBookSeries_Call {
	return &MockQuerier_UpdateBookSeries_Call{Call: _e.mock.On("UpdateBookSeries", ctx, arg)}
}

func (_c *MockQuerier_UpdateBookSeries_Call) Run(run func(ctx context.Context, arg UpdateBookSeriesParams)) *MockQuerier_UpdateBookSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UpdateBookSeriesParams
		if args[1] != nil {
			arg1 = args[1].(UpdateBookSeriesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateBookSeries_Call) Return(err error) *MockQuerier_UpdateBookSeries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_UpdateBookSeries_Call) RunAndReturn(run func(ctx context.Context, arg UpdateBookSeriesParams) error) *MockQuerier_UpdateBookSeries_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertAuthor provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpsertAuthor(ctx context.Context, name string) (Author, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for UpsertAuthor")
	}

	var r0 Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (Author, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) Author); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(Author)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpsertAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertAuthor'
type MockQuerier_UpsertAuthor_Call struct {
	*mock.Call
}

// UpsertAuthor is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQuerier_Expecter) UpsertAuthor(ctx interface{}, name interface{}) *MockQuerier_UpsertAuthor_Call {
	return &MockQuerier_UpsertAuthor_Call{Call: _e.mock.On("UpsertAuthor", ctx, name)}
}

func (_c *MockQuerier_UpsertAuthor_Call) Run(run func(ctx context.Context, name string)) *MockQuerier_UpsertAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpsertAuthor_Call) Return(author Author, err error) *MockQuerier_UpsertAuthor_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockQuerier_UpsertAuthor_Call) RunAndReturn(run func(ctx context.Context, name string) (Author, error)) *MockQuerier_UpsertAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertBook provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpsertBook(ctx context.Context, arg UpsertBookParams) (Book, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBook")
	}

	var r0 Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpsertBookParams) (Book, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpsertBookParams) Book); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(Book)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, UpsertBookParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpsertBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertBook'
type MockQuerier_UpsertBook_Call struct {
	*mock.Call
}

// UpsertBook is a helper method to define mock.On call
//   - ctx context.Context
//   - arg UpsertBookParams
func (_e *MockQuerier_Expecter) UpsertBook(ctx interface{}, arg interface{}) *MockQuerier_UpsertBook_Call {
	return &MockQuerier_UpsertBook_Call{Call: _e.mock.On("UpsertBook", ctx, arg)}
}

func (_c *MockQuerier_UpsertBook_Call) Run(run func(ctx context.Context, arg UpsertBookParams)) *MockQuerier_UpsertBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UpsertBookParams
		if args[1] != nil {
			arg1 = args[1].(UpsertBookParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpsertBook_Call) Return(book Book, err error) *MockQuerier_UpsertBook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockQuerier_UpsertBook_Call) RunAndReturn(run func(ctx context.Context, arg UpsertBookParams) (Book, error)) *MockQuerier_UpsertBook_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertSeries provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (Series, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertSeries")
	}

	var r0 Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpsertSeriesParams) (Series, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, UpsertSeriesParams) Series); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(Series)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, UpsertSeriesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_UpsertSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertSeries'
type MockQuerier_UpsertSeries_Call struct {
	*mock.Call
}

// UpsertSeries is a helper method to define mock.On call
//   - ctx context.Context
//   - arg UpsertSeriesParams
func (_e *MockQuerier_Expecter) UpsertSeries(ctx interface{}, arg interface{}) *MockQuerier_UpsertSeries_Call {
	return &MockQuerier_UpsertSeries_Call{Call: _e.mock.On("UpsertSeries", ctx, arg)}
}

func (_c *MockQuerier_UpsertSeries_Call) Run(run func(ctx context.Context, arg UpsertSeriesParams)) *MockQuerier_UpsertSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 UpsertSeriesParams
		if args[1] != nil {
			arg1 = args[1].(UpsertSeriesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpsertSeries_Call) Return(series Series, err error) *MockQuerier_UpsertSeries_Call {
	_c.Call.Return(series, err)
	return _c
}

func (_c *MockQuerier_UpsertSeries_Call) RunAndReturn(run func(ctx context.Context, arg UpsertSeriesParams) (Series, error)) *MockQuerier_UpsertSeries_Call {
	_c.Call.Return(run)
	return _c
}
