// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Book struct {
	ID              int64       `json:"id"`
	BookID          int64       `json:"book_id"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
	SeriesName      *string     `json:"series_name"`
	SeriesNumber    *float64    `json:"series_number"`
	Asin            *string     `json:"asin"`
	Isbn10          *string     `json:"isbn10"`
	Isbn13          *string     `json:"isbn13"`
	Language        *string     `json:"language"`
	HardcoverID     *string     `json:"hardcover_id"`
	HardcoverBookID *int64      `json:"hardcover_book_id"`
	GoodreadsID     *string     `json:"goodreads_id"`
	GoogleID        *string     `json:"google_id"`
	Data            interface{} `json:"data"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}

type Series struct {
	ID          int64       `json:"id"`
	SeriesID    int64       `json:"series_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Url         *string     `json:"url"`
	Data        interface{} `json:"data"`
}
