// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
)

type Author struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Book struct {
	ID              int64           `json:"id"`
	BookID          int64           `json:"book_id"`
	Title           string          `json:"title"`
	Description     string          `json:"description"`
	SeriesName      *string         `json:"series_name"`
	SeriesNumber    *float64        `json:"series_number"`
	Asin            *string         `json:"asin"`
	Isbn10          *string         `json:"isbn10"`
	Isbn13          *string         `json:"isbn13"`
	Language        *string         `json:"language"`
	HardcoverID     *string         `json:"hardcover_id"`
	HardcoverBookID *int64          `json:"hardcover_book_id"`
	GoodreadsID     *string         `json:"goodreads_id"`
	GoogleID        *string         `json:"google_id"`
	Data            json.RawMessage `json:"data"`
	SeriesID        *int64          `json:"series_id"`
	IsMissing       *bool           `json:"is_missing"`
}

type BookAuthor struct {
	BookID   int64 `json:"book_id"`
	AuthorID int64 `json:"author_id"`
}

type Configuration struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}

type Series struct {
	ID          int64           `json:"id"`
	SeriesID    int64           `json:"series_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Url         *string         `json:"url"`
	Data        json.RawMessage `json:"data"`
}

type SeriesAuthor struct {
	SeriesID int64 `json:"series_id"`
	AuthorID int64 `json:"author_id"`
}
